GET http://localhost:3000/blog/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuc2h1IiwiaWF0IjoxNjQ3MjUxODgwfQ.IOGfwPpYdZfnzlHRCYCnWar9fOrgH6dbW9cZdRXmjUk

###

POST http://localhost:3000/signup/
Content-Type: application/json

{    
    "username": "anshu",
    "password": "anshu@2021",
    "gender":"male",
    "location":"jhansi"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "anshu",
    "password": "anshu@2021"
}


